name: Action Test

on:
  push:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Update Latest tag
        uses: EndBug/latest-tag@v1.4.0
      - name: Set up clickhouse
        uses: metrico/clickhouse-server-action@latest
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run tests
        run: go test -v
        working-directory: test
