name: Action Test

on:
  push:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up clickhouse
        uses: metrico/clickhouse-server-action@v1.0.0
      - name: Dump docker logs
        uses: jwalton/gh-docker-logs@v1
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run tests
        run: go test -v
        working-directory: test
